name: CI
run-name: ${{ github.actor }} is running specs
on: [push]
jobs:
  Run-Specs:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: cd ${{ github.workspace }}
      - run: ./run_docker-compose.spec.sh
        env:
          FRIENDLYCLEANERCODEASSISTANT_SSH_KEY: ${{ secrets.FRIENDLYCLEANERCODEASSISTANT_SSH_KEY }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Run-Lint-JS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: cd ${{ github.workspace }}
      - run: ./run_docker-compose.lint.js.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Run-Lint-RB:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: cd ${{ github.workspace }}
      - run: ./run_docker-compose.lint.rb.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
